[Icon Theme]
Name=Aether-Icons
Comment=Modern sleek vector icon theme for AetherOS
Inherits=Papirus-Dark,Adwaita,hicolor
Directories=scalable/apps,scalable/places,scalable/devices,scalable/status,scalable/mimetypes,scalable/actions

[scalable/apps]
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/places]
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/devices]
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/status]
Size=24
Type=Scalable
MinSize=16
MaxSize=64

[scalable/mimetypes]
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/actions]
Size=24
Type=Scalable
MinSize=16
MaxSize=64
